language: rust
rust:
- stable
- beta
- nightly
sudo: false
after_success: ! '[ $TRAVIS_BRANCH = master ] &&

  [ $TRAVIS_PULL_REQUEST = false ] &&

  export PATH=$HOME/.local/bin:$PATH &&

  cargo doc &&

  echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d ''/''
  -f 2`/index.html>" > target/doc/index.html &&

  pip install --user ghp-import &&

  ghp-import -n target/doc &&

  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages

'
env:
  global:
    secure: I6sdhQJ6dcE5QFkGrB+OUpjcwmr7TiI+irmGeELLGFNlxAvSVo1i0XnpTfXaXwTPfyYCxtJ5YbUeavi23qqVXMv11fX/PcmRcMNiFbvEBgP9+qpA2xmC2U7BCkU3RndgkhmO3J4V8WB95x08hZRrzx2K8WF5KM8Rm7Nd66qXCKU7pwbBibOCh8032hIUlAYXV4Q6emOOCH8ZqS6GIBgIY91hl+TJyjKJZ2Tp2jBzPpBKpKcAlT8Tb+RcUUQw0D6jFgWUAXNQCoh6WCFz1xOWJAzLf5Tlq3/EbA8PHhW5J+bXhD2HFHXA7XOkchNJdO6WrTPHkjgy+jTK8NMACSpYRu9U/R8PqSznLiS1hlGi85OZ2PXk2A81OjKE+T8azJoeKETSdqoc/TGk2b+aApN03T3vlY1k4YLsVYCihuZ81WSemZ83mTXJ6c4028653JuK6a7qBJ9t3ZpKgbCE1o5FuIAMfKs+BOma6yufkJcA0ugGVFuv0NkxGrEanA1wWeBtCjiT0VosrtTVKihHAjZjY43tF+uWdW4y0bAykF/DS7JkXCzjGBXBOrgkd2ojnSyH6Y3tiQyE+Fv1tdHT6UkoVy4rVXRVnkcYuQMa/ED6o/Xv623Kj5MNu7gIXLEbeJwd66RUzmrkwEp2ReH5pBOnAR+ms27cf5tHFL+FOTNdrf8=
